[project]
name = "nicgiprep"
version = "0.1.0"
description = "NiGiPrep preprocessing pipelines"


[build-system]
requires = ["setuptools>=67.8.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"nicgiprep.data.labels_classes_priors" = ["*.npy"]
"nicgiprep.data.data_tutorial" = ["*"]